trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- script: |
    echo "Installing dependencies"
    brew install --cask android-sdk
    echo "Setting up Android SDK"
    yes | sdkmanager --licenses
    sdkmanager "platforms;android-29" "system-images;android-29;default;x86_64"
    echo "Creating and starting emulator"
    echo "no" | avdmanager create avd -n test -k "system-images;android-29;default;x86_64"
    $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window &
    sleep 30
  displayName: 'Setup AVD and Run Test'
  continueOnError: true


